name: Deploy GitHub Pages

# 触发条件：在 push 到 master/main 分支后
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 检查代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 安装hugo命令
      - name: Install Hugo
        run: sudo apt install hugo

      # 1、生成静态文件
      # 默认主题（config.toml)
      - name: Hugo Generate
        run: hugo #--config 

      # 2、部署到 GitHub Pages
      - name: Deploy on Github
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: daotoyi/FIRE
          BRANCH: gh-pages # 部署到 gh-pages 分支
          FOLDER: public
          #注意这里的 public 是仓库根目录下的 public
          # hugo生成的public/ 文件夹. 或者 docs/
